# Generated by Django 5.2.8 on 2025-11-27 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFinancialInstitution',
            fields=[
                ('Financial_institution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('dsa_code', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Financial Institution',
                'verbose_name_plural': 'Financial Institutions',
                'db_table': 'admin_financial_institution',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
