# Generated by Django 5.2.8 on 2025-11-27 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('bank_product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_products', to='Admin.adminfinancialinstitution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_products', to='Admin.product')),
            ],
            options={
                'db_table': 'bank_product_junction',
                'unique_together': {('bank', 'product')},
            },
        ),
    ]
